### ISSUE TITLE
MongoError: Topology was destroyed

### ISSUE THREAD

**Issue by CaioV1** [CaioV1/Helter-API#5]
When it's runned a integrated test the database driver excepts this error:

Unhandled error. (MongoError: Topology was destroyed

      at initializeCursor (node_modules/mongodb-core/lib/cursor.js:596:25)
      at nextFunction (node_modules/mongodb-core/lib/cursor.js:456:12)
      at Cursor.Object.<anonymous>.Cursor.next (node_modules/mongodb-core/lib/cursor.js:766:3)
      at Cursor.Object.<anonymous>.Cursor._next (node_modules/mongodb/lib/cursor.js:216:36)
      at fetchDocs (node_modules/mongodb/lib/operations/cursor_ops.js:217:12)
      at toArray (node_modules/mongodb/lib/operations/cursor_ops.js:247:3)
      at executeOperation (node_modules/mongodb/lib/utils.js:416:24)
      at Cursor.Object.<anonymous>.Cursor.toArray (node_modules/mongodb/lib/cursor.js:829:10)
      at node_modules/mquery/lib/collection/node.js:30:14
      at handleCallback (node_modules/mongodb/lib/utils.js:128:55)
      at Collection.<anonymous> (node_modules/mongodb/lib/collection.js:431:45)
      at Collection.deprecated [as find] (node_modules/mongodb/lib/utils.js:677:15)
      at NativeCollection.<computed> [as find] (node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:158:28)
      at NodeCollection.Object.<anonymous>.NodeCollection.find (node_modules/mquery/lib/collection/node.js:26:19)
      at model.Query.<anonymous> (node_modules/mongoose/lib/query.js:1867:20)
      at model.Query._wrappedThunk [as _find] (node_modules/mongoose/lib/helpers/query/wrapThunk.js:16:8) {
        name: 'MongoError',
        [Symbol(mongoErrorContextSymbol)]: {}
      })Error [ERR_UNHANDLED_ERROR]: Unhandled error. (MongoError: Topology was destroyed
      at initializeCursor (node_modules/mongodb-core/lib/cursor.js:596:25)
      at nextFunction (node_modules/mongodb-core/lib/cursor.js:456:12)
      at Cursor.Object.<anonymous>.Cursor.next (node_modules/mongodb-core/lib/cursor.js:766:3)
      at Cursor.Object.<anonymous>.Cursor._next (node_modules/mongodb/lib/cursor.js:216:36)
      at fetchDocs (node_modules/mongodb/lib/operations/cursor_ops.js:217:12)
      at toArray (node_modules/mongodb/lib/operations/cursor_ops.js:247:3)
      at executeOperation (node_modules/mongodb/lib/utils.js:416:24)
      at Cursor.Object.<anonymous>.Cursor.toArray (node_modules/mongodb/lib/cursor.js:829:10)
      at node_modules/mquery/lib/collection/node.js:30:14
      at handleCallback (node_modules/mongodb/lib/utils.js:128:55)
      at Collection.<anonymous> (node_modules/mongodb/lib/collection.js:431:45)
      at Collection.deprecated [as find] (node_modules/mongodb/lib/utils.js:677:15)
      at NativeCollection.<computed> [as find] (node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:158:28)
      at NodeCollection.Object.<anonymous>.NodeCollection.find (node_modules/mquery/lib/collection/node.js:26:19)
      at model.Query.<anonymous> (node_modules/mongoose/lib/query.js:1867:20)
      at model.Query._wrappedThunk [as _find] (node_modules/mongoose/lib/helpers/query/wrapThunk.js:16:8) {
        name: 'MongoError',
        [Symbol(mongoErrorContextSymbol)]: {}
      })
      at node_modules/mongoose/lib/model.js:4464:13
      at node_modules/mongoose/lib/query.js:4272:14
      at cb (node_modules/mongoose/lib/query.js:1837:14)
      at node_modules/mongodb/lib/utils.js:411:14
      at executeCallback (node_modules/mongodb/lib/utils.js:401:25)
      at handleCallback (node_modules/mongodb/lib/utils.js:128:55)
      at node_modules/mongodb/lib/operations/cursor_ops.js:220:38
      at ClientSession.endSession (node_modules/mongodb-core/lib/sessions.js:134:41)
      at Cursor.Object.<anonymous>.Cursor._endSession (node_modules/mongodb-core/lib/cursor.js:190:13)

**Comment by CaioV1** [comment]
The solution was to remove the middleware to disconnect from the database after every request and disconnect only when the application shuts down  according to the mongoose oficial faq (https://mongoosejs.com/docs/faq.html#creating_connections). To solve the test issue of not finishing the execution I had to put a function afterAll with the mongoose's method disconnect to shut the connection and finish the integrated test.
